baseurl = "https://grazercomputerclub.github.io/Blog"
title = "GC2 Blog"
theme = "hugo-nederburg-theme"
languageCode = "de-de"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-130665257-1"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[params]
  # Unmark to use post folder for images. Default is static folder.
  #usepostimgfolder = true
  slogan = "Infos rund um Computer, Programmierung, Elektronik und sonstige Informatik"
  description = "Blog des Grazer Computer Club - GC2" # meta description
  # You need to set author to have an author bio. If you have a writer in the markdown file it will override this.
  author = "GC2"
  authorLink = "https://gc2.at"
  bio = [
    "GC2 - Grazer Computer Club e. V.",
    "ZVR: 1093020071",
    "Rechtlicher Sitz: Graz"
  ]
  copyright = [
    "CC-BY-4.0 https://creativecommons.org/licenses/by/4.0/",
    "2018, Grazer Computer Club e. V.",
    "Nederburg Hugo Theme by [Appernetic](https://appernetic.io).",
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "blog@gc2.at"

  # Nav links in the side bar
  [[menu.main]]
  name = "Blog (Deutsch)"
  url = "https://grazercomputerclub.github.io/Blog/index.html"
  weight = 1

  [[menu.main]]
  name = "Blog (English)"
  url = "https://grazercomputerclub.github.io/BlogEN/index.html"
  weight = 1

  [[menu.main]]
  name = "Impressum"
  url = "impressum/"
  weight = 2

# [[menu.main]]
# name = "Kontakt"
# url = "contact/"
# weight = 3

  [[menu.main]]
  name = "Hauptseite"
  url = "http://gc2.at"
  weight = 4

# this will also be in author bio if there is no writer.
  [params.social]
  email         = "blog@gc2.at"
  twitter       = "https://twitter.com/_gc2_"
  github        = "https://github.com/GrazerComputerClub/"
  rss           = true

# Add a writer, then use it in the markdown front matter like this: writer = "Martin Strohmayer"
  [params.writers]
    [params.writers."Martin Strohmayer"]
    link = "http://strohmayers.com"
    email = "martin.strohmayer@gc2.at"
    bio = [
      "Programmierer und Raspberry Pi Experte."
    ]
    twitter       = "https://twitter.com/m_stroh"
    github        = "https://github.com/mstroh76"


